### ISSUE TITLE
[Feature] Space support between "//" and <Tag>

### ISSUE THREAD

**Issue by Magicolo** [densylkin/Unity-ToDo#1]
I already have many tags in my scripts and I've taking the habit of putting a space between the "//" and the tag for neatness. Could you modify the regex to support spaces between the "//" and <Tag> in ScriptParser.cs (line 34)?

**Comment by densylkin** [comment]
Thanks for idea. Added this in last [commit](https://github.com/densylkin/Unity-ToDo/commit/8b78f010ef35323d4601650e67c4a5630192330d)
